import "~/styles/globals.css";

import { type Metadata } from "next";
import { Montserrat, Rubik_Broken_Fax } from "next/font/google";
import Link from "next/link";

export const metadata: Metadata = {
  title: "CRTV_Shelves",
  description:
    "App by Ashton Christensen, somewhere for people who want to show off their top fav's in any and all of their hobbies. Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body className="flex h-screen flex-col bg-black">
        <div className="flex flex-1 overflow-hidden border-t border-r-2 border-gray-800 bg-gray-950">
          <div className="flex-1 overflow-y-auto">{children}</div>
        </div>
        {/* <div className="thankyous text-white">
          <a
            target="_blank"
            href="https://icons8.com/icon/m5sL5chjsPar/shelves"
          >
            Shelves
          </a>{" "}
          icon by{" "}
          <a target="_blank" href="https://icons8.com">
            Icons8
          </a>
        </div> */}
      </body>
    </html>
  );
}
